# Application Name
spring.application.name=bean-organized

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Mostra o SQL formatado no console para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bean-organized
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JDBC
spring.data.jdbc.repositories.enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.partitions=1
kafka.topic.replication-factor=1


