# Application Name
spring.application.name=InternalBRBeanOrganizedProcessor

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL formatado no console para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bean-organized
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JDBC
spring.data.jdbc.repositories.enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.partitions=1
kafka.topic.replication-factor=1

# Mail Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=<usr>
spring.mail.password=<pwd>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


